// <auto-generated />
using InventoryModule.src.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryModule.src.data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryModule.src.model.Inventario", b =>
                {
                    b.Property<string>("id_inventario")
                        .HasColumnType("text");

                    b.Property<string>("id_producto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("stock_actual")
                        .HasColumnType("integer");

                    b.Property<int?>("stock_disponible")
                        .HasColumnType("integer");

                    b.Property<int>("stock_reservado")
                        .HasColumnType("integer");

                    b.HasKey("id_inventario");

                    b.HasIndex("id_producto");

                    b.ToTable("inventarios", (string)null);
                });

            modelBuilder.Entity("InventoryModule.src.model.Productos", b =>
                {
                    b.Property<string>("id_producto")
                        .HasColumnType("text");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("id_proveedor")
                        .HasColumnType("text");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("precio_compra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("precio_venta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("umbral_alerta_stock_bajo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("id_producto");

                    b.HasIndex("id_proveedor");

                    b.HasIndex("sku")
                        .IsUnique();

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("InventoryModule.src.model.Proveedor", b =>
                {
                    b.Property<string>("id_proveedor")
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("numero_telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("producto_que_vende")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("id_proveedor");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("InventoryModule.src.model.Inventario", b =>
                {
                    b.HasOne("InventoryModule.src.model.Productos", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventoryModule.src.model.Productos", b =>
                {
                    b.HasOne("InventoryModule.src.model.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("id_proveedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("InventoryModule.src.model.Productos", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("InventoryModule.src.model.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
